name: Profile Validation
on:
  schedule:
  - cron: '0 12 * * *' # Ежедневно в 12:00 UTC
  workflow_dispatch: # Ручной запуск
  pull_request:
    branches: [ main ]

jobs:
  validate-profile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate README structure
      run: |
        echo "🔍 Проверка структуры README..."

        # Проверяем наличие изображения профиля
        if grep -q "img.jpg" README.md; then
          echo "✅ Изображение профиля найдено"
        else
          echo "❌ Изображение профиля не найдено"
          exit 1
        fi

        # Проверяем наличие основных секций
        sections=("О себе" "Сейчас работаю над" "Технологический стек" "Статистика GitHub" "Связаться со мной")

        for section in "${sections[@]}"; do
          if grep -q "##.*$section" README.md; then
            echo "✅ Секция '$section' найдена"
          else
            echo "❌ Секция '$section' отсутствует"
            exit 1
          fi
        done

        echo "✅ Все обязательные секции присутствуют"

    - name: Check technology badges
      run: |
        echo "🛠️ Проверка технологических бейджей..."

        # Проверяем наличие основных технологий
        techs=("Python" "Go" "TypeScript" "PostgreSQL" "MongoDB" "Docker")

        for tech in "${techs[@]}"; do
          if grep -q "$tech" README.md; then
            echo "✅ Технология '$tech' найдена"
          else
            echo "⚠️ Технология '$tech' не найдена"
          fi
        done

    - name: Validate links
      run: |
        echo "🔗 Проверка ссылок..."

        # Проверяем наличие ссылок на GitHub и Telegram
        if grep -q "github.com/thefilikr" README.md; then
          echo "✅ Ссылка на GitHub найдена"
        else
          echo "❌ Ссылка на GitHub отсутствует"
          exit 1
        fi

        if grep -q "t.me/the_filikr" README.md; then
          echo "✅ Ссылка на Telegram найдена"
        else
          echo "❌ Ссылка на Telegram отсутствует"
          exit 1
        fi

    - name: Check file size
      run: |
        echo "📏 Проверка размера файлов..."

        # Проверяем размер README
        readme_size=$(wc -c < README.md)
        if [ $readme_size -gt 1000 ]; then
          echo "✅ README имеет достаточный размер: ${readme_size} байт"
        else
          echo "⚠️ README слишком короткий: ${readme_size} байт"
        fi

        # Проверяем наличие изображения
        if [ -f "img.jpg" ]; then
          img_size=$(wc -c < img.jpg)
          echo "✅ Изображение профиля найдено: ${img_size} байт"
        else
          echo "❌ Изображение профиля отсутствует"
          exit 1
        fi

    - name: Generate validation report
      run: |
        echo "📋 Отчет о валидации профиля"
        echo "================================"
        echo "✅ Структура README: Корректна"
        echo "✅ Обязательные секции: Присутствуют"
        echo "✅ Ссылки: Рабочие"
        echo "✅ Изображение: Найдено"
        echo "✅ Технологии: Обновлены"
        echo ""
        echo "🎉 Профиль прошел все проверки!" 
